[2022-09-28 01:16:14,228] {processor.py:163} INFO - Started process (PID=48) to work on /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:16:14,241] {processor.py:642} INFO - Processing file /opt/airflow/dags/data_upload_to_gcs.py for tasks to queue
[2022-09-28 01:16:14,260] {logging_mixin.py:109} INFO - [2022-09-28 01:16:14,260] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:16:14,762] {logging_mixin.py:109} INFO - [2022-09-28 01:16:14,761] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/data_upload_to_gcs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_upload_to_gcs.py", line 11
    file_path = "C:\Users\Febian\Desktop\IYKRA"
               ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2022-09-28 01:16:14,953] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:16:15,031] {processor.py:171} INFO - Processing /opt/airflow/dags/data_upload_to_gcs.py took 0.806 seconds
[2022-09-28 01:16:46,225] {processor.py:163} INFO - Started process (PID=76) to work on /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:16:46,378] {processor.py:642} INFO - Processing file /opt/airflow/dags/data_upload_to_gcs.py for tasks to queue
[2022-09-28 01:16:46,390] {logging_mixin.py:109} INFO - [2022-09-28 01:16:46,390] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:16:46,813] {logging_mixin.py:109} INFO - [2022-09-28 01:16:46,765] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/data_upload_to_gcs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_upload_to_gcs.py", line 11
    file_path = "C:\Users\Febian\Desktop\IYKRA"
               ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2022-09-28 01:16:46,923] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:16:47,025] {processor.py:171} INFO - Processing /opt/airflow/dags/data_upload_to_gcs.py took 0.896 seconds
[2022-09-28 01:17:17,431] {processor.py:163} INFO - Started process (PID=92) to work on /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:17:17,439] {processor.py:642} INFO - Processing file /opt/airflow/dags/data_upload_to_gcs.py for tasks to queue
[2022-09-28 01:17:17,458] {logging_mixin.py:109} INFO - [2022-09-28 01:17:17,443] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:17:17,538] {logging_mixin.py:109} INFO - [2022-09-28 01:17:17,524] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/data_upload_to_gcs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_upload_to_gcs.py", line 11
    file_path = "C:\Users\Febian\Desktop\IYKRA"
               ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2022-09-28 01:17:17,580] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:17:17,599] {processor.py:171} INFO - Processing /opt/airflow/dags/data_upload_to_gcs.py took 0.174 seconds
[2022-09-28 01:17:47,987] {processor.py:163} INFO - Started process (PID=117) to work on /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:17:48,001] {processor.py:642} INFO - Processing file /opt/airflow/dags/data_upload_to_gcs.py for tasks to queue
[2022-09-28 01:17:48,028] {logging_mixin.py:109} INFO - [2022-09-28 01:17:48,027] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:17:48,207] {logging_mixin.py:109} INFO - [2022-09-28 01:17:48,206] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/data_upload_to_gcs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_upload_to_gcs.py", line 11
    file_path = "C:\Users\Febian\Desktop\IYKRA"
               ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2022-09-28 01:17:48,269] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:17:48,307] {processor.py:171} INFO - Processing /opt/airflow/dags/data_upload_to_gcs.py took 0.334 seconds
[2022-09-28 01:18:19,076] {processor.py:163} INFO - Started process (PID=142) to work on /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:18:19,078] {processor.py:642} INFO - Processing file /opt/airflow/dags/data_upload_to_gcs.py for tasks to queue
[2022-09-28 01:18:19,088] {logging_mixin.py:109} INFO - [2022-09-28 01:18:19,087] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:18:19,180] {logging_mixin.py:109} INFO - [2022-09-28 01:18:19,178] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/data_upload_to_gcs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_upload_to_gcs.py", line 11
    file_path = "C:\Users\Febian\Desktop\IYKRA"
               ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2022-09-28 01:18:19,233] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:18:19,255] {processor.py:171} INFO - Processing /opt/airflow/dags/data_upload_to_gcs.py took 0.185 seconds
[2022-09-28 01:18:50,090] {processor.py:163} INFO - Started process (PID=165) to work on /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:18:50,091] {processor.py:642} INFO - Processing file /opt/airflow/dags/data_upload_to_gcs.py for tasks to queue
[2022-09-28 01:18:50,094] {logging_mixin.py:109} INFO - [2022-09-28 01:18:50,093] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:18:50,178] {logging_mixin.py:109} INFO - [2022-09-28 01:18:50,176] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/data_upload_to_gcs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_upload_to_gcs.py", line 11
    file_path = "C:\Users\Febian\Desktop\IYKRA"
               ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2022-09-28 01:18:50,227] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:18:50,279] {processor.py:171} INFO - Processing /opt/airflow/dags/data_upload_to_gcs.py took 0.186 seconds
[2022-09-28 01:19:20,386] {processor.py:163} INFO - Started process (PID=178) to work on /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:19:20,388] {processor.py:642} INFO - Processing file /opt/airflow/dags/data_upload_to_gcs.py for tasks to queue
[2022-09-28 01:19:20,392] {logging_mixin.py:109} INFO - [2022-09-28 01:19:20,392] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:19:20,554] {logging_mixin.py:109} INFO - [2022-09-28 01:19:20,552] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/data_upload_to_gcs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_upload_to_gcs.py", line 11
    file_path = "C:\Users\Febian\Desktop\IYKRA"
               ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2022-09-28 01:19:20,600] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:19:20,653] {processor.py:171} INFO - Processing /opt/airflow/dags/data_upload_to_gcs.py took 0.271 seconds
[2022-09-28 01:19:51,611] {processor.py:163} INFO - Started process (PID=204) to work on /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:19:51,617] {processor.py:642} INFO - Processing file /opt/airflow/dags/data_upload_to_gcs.py for tasks to queue
[2022-09-28 01:19:51,624] {logging_mixin.py:109} INFO - [2022-09-28 01:19:51,623] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:19:51,681] {logging_mixin.py:109} INFO - [2022-09-28 01:19:51,680] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/data_upload_to_gcs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_upload_to_gcs.py", line 11
    file_path = "C:\Users\Febian\Desktop\IYKRA"
               ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2022-09-28 01:19:51,717] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:19:51,738] {processor.py:171} INFO - Processing /opt/airflow/dags/data_upload_to_gcs.py took 0.131 seconds
[2022-09-28 01:20:22,272] {processor.py:163} INFO - Started process (PID=230) to work on /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:20:22,281] {processor.py:642} INFO - Processing file /opt/airflow/dags/data_upload_to_gcs.py for tasks to queue
[2022-09-28 01:20:22,282] {logging_mixin.py:109} INFO - [2022-09-28 01:20:22,282] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:20:22,324] {logging_mixin.py:109} INFO - [2022-09-28 01:20:22,323] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/data_upload_to_gcs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_upload_to_gcs.py", line 11
    file_path = "C:\Users\Febian\Desktop\IYKRA"
               ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2022-09-28 01:20:22,351] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:20:22,370] {processor.py:171} INFO - Processing /opt/airflow/dags/data_upload_to_gcs.py took 0.137 seconds
[2022-09-28 01:20:52,594] {processor.py:163} INFO - Started process (PID=255) to work on /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:20:52,598] {processor.py:642} INFO - Processing file /opt/airflow/dags/data_upload_to_gcs.py for tasks to queue
[2022-09-28 01:20:52,602] {logging_mixin.py:109} INFO - [2022-09-28 01:20:52,602] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:20:52,640] {logging_mixin.py:109} INFO - [2022-09-28 01:20:52,639] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/data_upload_to_gcs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_upload_to_gcs.py", line 11
    file_path = "C:\Users\Febian\Desktop\IYKRA"
               ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2022-09-28 01:20:52,720] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/data_upload_to_gcs.py
[2022-09-28 01:20:52,793] {processor.py:171} INFO - Processing /opt/airflow/dags/data_upload_to_gcs.py took 0.203 seconds
